### ISSUE TITLE
需求讨论

### ISSUE THREAD

**Issue by ElfSundae** [kevinzheng/laravel-switchable-mail#1]
除了根据邮箱域名选择不同的 mailer driver ，还有没有别的使用场景？

**Comment by kvzn** [comment]
@ElfSundae 你是指在同一mail driver下切换不同配置(账号)的场景？

**Comment by ElfSundae** [comment]
嗯，同一 driver 不同配置的情况可能比较少，如果要改成这样的话，就需要接管 Laravel Mail 关于各个 transport 的配置。这种需求暂不考虑了。
考虑下根据 message 选择 driver 还可能有什么样的需求？

**Comment by kvzn** [comment]
其它的暂时还没想到，但发现了一个逻辑漏洞，由于Swift_Message的$to变量是个array，是不是说一个send调用是可以发送到多个地址的，那如果$to中包含多个需要不同mail driver发送的目标地址时，更严谨的办法是不是需要把send调用拆成几个使用不同mail driver的send调用？
```php
$to = $message->getTo();
$address = array_keys($to)[0];
```

**Comment by ElfSundae** [comment]
跟我们平时发邮件一样的，收件人可以是多个。
我重构了一下核心，你看下 develop 分支，顺便测试下 :)
现在的 driver 判断逻辑是有点问题，我下午抽空改改。

**Comment by ElfSundae** [comment]
Swift_Mailer 的 `getTo` 是一个数组，`['邮箱地址' => '名字', ...]`，我们只需要处理邮箱域名就行了。
外部调用 send 时如果传了多个收件人，肯定是希望在同一封邮件里发送给这些人，我们不应该给拆分发送。
driver 命中暂时先按「严格模式」来，也就是说如果配置了 qq.com 用 mailgun，也就是说只要收件人列表里出现 qq 邮箱的地址一次，本次发送就使用 mailgun 。
我现在是这样的计划，你觉得呢？

**Comment by ElfSundae** [comment]
`determineMailDriver` 改好了，已提交到 develop 分支 82eca09 。
现在的规则是：将收件人列表（包括 to, reply-to, cc, bcc）和配置文件中各个 driver 对应的邮箱域名列表相比较，如果某 driver 的域名列表能匹配到任意一个收件人的邮箱域名，则使用该 driver 发送这封邮件；如果有多个 driver 能够匹配，则按照配置文件中 driver 的顺序使用第一个。

**Comment by kvzn** [comment]
嗯，我觉得严格模式是目前最合理的，这是我之前没有想到的，我测试下代码先。

**Comment by ElfSundae** [comment]
cd348b2 已修复 forceReconnection 总是使用默认的 SwiftMailer.

晚上再把 failedRecipients 处理下。

**Comment by ElfSundae** [comment]
刚看了下，Mailer 的 failedRecipients 不需要处理。
`Mailer::failures` 总是返回最新（最后一次发送）的失败收件人列表。

**Comment by kevinzheng** [comment]
有个地方不太理解，如果`MailServiceProvider`中不`registerSwiftTransport`，而在`app.php`中我们也用`MailServiceProvider`替换了Laravel的`MailServiceProvider`，那么好像就没有地方会register `$app['swift.transport']`，那这里直接使用的`$app['swift.transport']`是在哪里注册的？
```php
    protected function registerSwiftMailerManager()
    {
        $this->app->singleton('swift.mailer.manager', function ($app) {
            return (new SwiftMailerManager($app))
                ->setTransportManager($app['swift.transport']);
        });
    }
```

**Comment by kvzn** [comment]
测试过了，没什么问题，已经merge了，打了tag 1.2 。研读了你的代码，受益非常多，大大地赞👍👍👍。

**Comment by ElfSundae** [comment]
刚把 Mailer 的 setSwiftMailer 处理了下，已合并到 master 分支。你再测试下。

**Comment by ElfSundae** [comment]
Laravel Mail 相关的已经处理完了，我这边暂未发现有冲突或遗漏的地方。

目前有一个不太优雅的地方就是选择 driver 的 `MailDriver`，不知道别人还有没有其他特殊需求.. 先这样吧，后面再考虑升级这块 😆 

建议把 README 再写详细点。这种需求在国内应该比较常见，可以加个中文版 README 或者在 phphub 上发个帖。 🎉

**Comment by kvzn** [comment]
在phphub上发了一个帖子，分享给了大家，https://laravel-china.org/topics/3306  ， 💪💪

**Comment by ElfSundae** [comment]
9b76075 

- 优化了 `MailDriver::forMessage` ：如果没有配置 `switchable-mail` 就直接使用默认 driver，不再计算收件人域名列表。
- `SwiftMailerManager` 添加 `resetMailer($mailer)` 和 `resetMailers()`  用于清理缓存。

**Comment by ElfSundae** [comment]
6de3451

- 优化类结构，将 `Swift_Message` 的帮助方法移至新建类 `SwiftMessageHelper`。

已合并到 master 分支，测试没问题的话打个tag 🚀

**Comment by kvzn** [comment]
测试过了，looks good，tagged 1.3 😁

**Comment by ElfSundae** [comment]
这个项目暂告一段落了。
我 fork 了一个 [laravel-multi-mail](https://github.com/ElfSundae/laravel-multi-mail)，准备闲了填填坑... 
刚删除 tag 时不小心把这边的 1.0 也给删了 😞  ，可以把我从 Collaborator 移除了，以后有更新我提交 PR。

**Comment by kvzn** [comment]
好的😁
